---
title: "2018-0605 assignment Takaya"
author: "Hisamitsu Takaya"
date: "2018/6/6"
output: html_document
---

Make a tree with 10 leaf-nodes and draw the tree on a paper by hands.
Then, generate an edge list.
Also generate a adjacency matrix.

Make a graph object of the tree by two ways; using the edge list and the adjacency matrix.
Give positive integer values to the edges and provide the edge weight to the graph object(s).
Obtain pairwise distance matrix between all vertex pairs.

```{r}
library(igraph)

# Generate an edge list
edges <-  c(1,2,2,3,3,4,3,5,4,6,4,7,2,8,8,9,8,10,1,11,11,12,11,13,13,14,11,15,15,16,15,17,1,18)
tree_e <- graph(edges,directed=F)
plot(tree_e,main="Tree from Edge List")

# Generate an adjacency matrix
e_mat <- matrix(edges,byrow=T,ncol=2)
n_node <- max(edges)
A_matrix <- matrix(rep(0,n_node^2),n_node,n_node)
for(i in 1:dim(e_mat)[1]){
  r <- e_mat[i,1]
  c <- e_mat[i,2]
  A_matrix[r,c] <- 1
}
A_matrix <- A_matrix + t(A_matrix)
tree_m <- graph_from_adjacency_matrix(A_matrix,mode="undirected")
plot(tree_m,main="Tree from Adjacency Matrix")
```


```{r}
# Assign random weights to each edges
weight <- sample(1:10,length(E(tree_e)),replace=T)
E(tree_e)$weight <- weight
edge_attr(tree_e)
```


```{r}
# Call a ditance matrix 
distances(tree_e)
```

