# 階数(Rank)
# In linear algebra, the rank of a matrix is the dimension of the vector space generated by its columns.
# It is the same as the dimension of the space by its rows.
# 行列の中の1次独立な列ベクトルの最大本数

# 行列式(Determinant)
# defined only w/ square matrix. 
# it can be viewed as the scaling factor of the transformation described by the matrix.
# If det(A) is zero, it means that matrix A doesn't have the inverse matrix.

# トレース(跡) (Trace)
# sum of the diagonal elements

# 固有値(Eigen values)
# 行列Aによって Av = λvを満たすとすると、 vが固有ベクトル(ゼロではない)でλが固有値

# assignment affine transformation
# matrix moves a point (x, 0) to (x, ax).
# m and n could be any real number
M1 <- matrix(c(1, a, m, n), 2, 2)
# matrix moves a point (x, 0) to (x, ax+b).
# m and n could be any real number
M2 <- matrix(c(a, a, 0, m, n, 0, 0, b, 0), 3, 3)
# matrix that moves (x1,x2,0) to (a1x1 + a2x2,b1x1+b2x2)
M3 <- matrix(c(a1, a2, m, b1, b2, n), nrow=2, byrow=T)
# matrix that moves (x1,x2,0) to (a1x1+a2x2+c,b1x1+b2x2+d)
M4 <- matrix(c(a1, a2, m, c, b1, b2, n, d), nrow=2, byrow=T)